image: ruby:2.3
variables:
  GIT_SSL_NO_VERIFY: "true"
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - export RUBYOPT="-KU -E utf-8:utf-8"
  - export http_proxy=http://194.213.41.2:8080
  - export no_proxy="git.servis.justice.cz"

stages:
  - test
  - deploy

test:2.3:
  services:
    - postgres
  script:
    - BASE_URL=`echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - REPO_URL="$BASE_URL/libraries/egon_gate.git"
    - REPO_DIR=libraries/egon_gate
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    - "sed -i \"s|gem 'egon_gate', path: '.*'|gem 'egon_gate', path: '$REPO_DIR'|g\" Gemfile"
    - REPO_URL="$BASE_URL/libraries/azahara_schema.git"
    - REPO_DIR=libraries/azahara_schema
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    - "sed -i \"s|gem 'azahara_schema', path: '.*'|gem 'azahara_schema', path: '$REPO_DIR'|g\" Gemfile"
    - git config --global http.proxy 194.213.41.2:8080
    - REPO_URL="$BASE_URL/libraries/egov_utils-rails.git"
    - REPO_DIR=libraries/egov_utils
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    - "sed -i \"s|gem 'egov_utils', path: '.*'|gem 'egov_utils', path: '$REPO_DIR'|g\" Gemfile"
    - git config --global http.proxy 194.213.41.2:8080
    - http_proxy=194.213.41.2:8080 RAILS_ENV=test bundle install
    - cp config/database.yml.gitlabci config/database.yml
    - rake db:migrate RAILS_ENV=test
    - rspec

deploy_staging:
  stage: deploy
  script:
    - 'which ssh-agent || apk add --update openssh'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$PRODUCTION_USER_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - sed -n ':a;N;$!ba;s/\n/ /g' ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - gem install capistrano-rails
    - cap staging deploy
  environment:
    name: staging
  only:
    - master
  when: manual
